apiVersion: v1
kind: Service
metadata:
  name: github-actions-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: github-actions-demo
  sessionAffinity: None
  type: LoadBalancer