name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ./test.yml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        uses: ./build.yml

