jobs:
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn -B test
      - name: Run code coverage
        run: mvn jacoco:prepare-agent test jacoco:report
      - name: Upload Verify Artifact
        uses: actions/upload-artifact@v2
        with:
          name: verify
          path: |
                 target/surefire-reports/
                 target/site/jacoco/
